#!/usr/bin/env bash                                                             
# getting Apache to run on container                                                     

echo "Hello Holberton" > /var/www/html/index.html
